Feature/templates transfer
rubygarage/rubyhub pull request #11
Opened 2020-03-26 11:36 UTC by Bulatkin

**Improvements**

- Extracted PullRequest description from config to separate files with the ability to load different templates.

- Added check for template existence logic and its tests

**Fixed**

- Resolved Metrics/AbcSize in ```Rubyhub::Operations::PullRequest::Create``` method ```call```

- Minor fixes

2020-03-27 08:38 UTC, Volosh1n reviewed
please, rethink logic. we use [this](https://github.com/rubygarage/rubyhub/blob/master/lib/rubyhub/pull_request.rb) file to add descriptions

2020-03-27 08:38 UTC, Volosh1n commented on lib/rubyhub/config/templates/.frontend_description.txt
> +### Before submitting the merge request make sure the following are checked
description will be equal for both frontend abd backend teams. itshould be the same file.

2020-03-27 08:38 UTC, Volosh1n commented on lib/rubyhub/operations/pull_request/create.rb
> +            check_template_existence
please, remove those blank lines.

2020-03-27 08:38 UTC, Volosh1n commented on lib/rubyhub/operations/pull_request/create.rb
> +            @data
This is not good approach.
Check [this](https://github.com/rubygarage/rubyhub/blob/master/lib/rubyhub/pull_request.rb) file's method `message`. You should modify it to change current logic of adding descripion

2020-03-30 13:32 UTC, closed without merging

2020-03-30 13:47 UTC, dzemlianoi-double requested changes

2020-03-30 13:47 UTC, dzemlianoi-double commented on lib/rubyhub/config/templates/.frontend_description.txt
> +### Before submitting the merge request make sure the following are checked
it wouldn't be default template

Consider that it might have(or not) template OR could have description