Feature | PEO-1017
rubygarage/rubyhub pull request #12
Opened 2020-03-27 08:55 UTC by Bulatkin

JIRA ticket - https://garage.atlassian.net/browse/PEO-1017

### Before submitting the merge request make sure the following are checked
- [ ] Followed the style guidelines of this project
- [ ] Performed a self-review of own code
- [ ] Wrote the tests that prove that fix is effective/that feature works
- [ ] Check correctness of commit names/branch name/assignees list/labels
### Notable changes
- Describe all the changes in PR with a list
### Commands to run
- If PR contains Rake tasks/seeds/credentials changes - describe them below with a list

2020-03-27 17:26 UTC, Volosh1n requested changes

2020-03-27 17:26 UTC, Volosh1n commented on .circleci/config.yml
> +
I'd suggest to move it to another [workflow](https://github.com/rubygarage/circledge/blob/master/intro_to_circleci.md#workflows) 'linters'.

2020-03-30 13:39 UTC, Volosh1n requested changes

2020-03-30 13:39 UTC, Volosh1n commented on .circleci/config.yml
> +      - test
```yml
workflows:
  version: 2
  build:
    jobs:
      - lintering
      - specs
        requires:
          - lintering
```
It should be two separated jobs - one for lintering, another one for specs.
One job requires another - second job shouldn't start if first job failed.

2020-03-30 13:39 UTC, Volosh1n commented on .circleci/config.yml
> +            export SPEC_OPTS="--format documentation --format RspecJunitFormatter --out tmp/rspec/rspec-${CIRCLE_NODE_INDEX:-0}.xml"
what is it? Commands should be small

2020-03-31 13:06 UTC, closed without merging

2020-03-31 13:06 UTC, Bulatkin commented
Moved changes to Feature | PEO-1023